console.log("This is loaded from the external js");
alert("This is an alert!");
var name= prompt("What is your name?");
var school= prompt("What school do you go to?");
let hobby= prompt("What do you like to do?");
console.log(`Name: ${name}`);
console.log(`School: ${school}`);
console.log(`Hobby: ${hobby}`);
document.getElementbyId("name").innerHTML = "<b>Name; </b>"+name;
document.getElementbyId("school").innerHTML = "<b>School; </b>"+school;
document.getElementbyId("hobby").innerHTML = "<b>Hobby; </b>"+hobby;
