console.log("This is loaded from the external js");
alert("This is an alert!");
var name= "Chase Mobley";
var school= "JCSU";
let hobby= "Gaming";
console.log(`Name: ${name}`);
console.log(`School: ${school}`);
console.log(`Hobby: ${hobby}`);
document.getElementbyId("name").innerHTML = "<b>Name; </b>"+name;
document.getElementbyId("school").innerHTML = "<b>School; </b>"+school;
document.getElementbyId("hobby").innerHTML = "<b>Hobby; </b>"+hobby;
